production:
  secret_key_base: 0e1a841a2c1d2c17f31031041fb235ec8e60b498bba3a83616930e37c884fe6e1d89a88aca34457834b907c997cb166e9b0186b5b3c223eaefbb7e88822$
  base_url: http://walletbuddy.flogic.in
  REDIS:
   server: 127.0.0.1
   port: 6379
  use_s3_for_storage: true
  maps_api_key: AIzaSyAzzgR33zb3Fv_GuCd3ix9WFRKI2Pnv75c
  AWS:
    s3_bucket: walletbuddy-stg
    s3_region: ap-south-1
    access_key_id: AKIAIEGZVKRCPSRYOZVQ
    secret_access_key: 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
  CASHFREE:
    payment_client_id: 67529edbf08b41c0e4d7e9402576
    payment_client_key: 57d7f1950c022bd20e8a9a34953c471f26a813e5
    payment_client_salt: eCwWELxi
    url: https://www.cashfree.com
    api_url: https://api.cashfree.com
    payout_id: CF6752D4XGIBZTBK6EUYE
    payout_secret: 682d143e5f1b6c4297d84dc7cd899038631d5230
    payout_url: https://payout-api.cashfree.com/payout/v1
  PAYU_HEALTHPASS:
    id: 112837
    key: ZJbuPe
    salt: JobkA4hP
    url: https://test.payu.in/_payment
  AUTH0:
    client_id: aiPa1ka9mts1lq5xUCqiSYZC729GWLXg 
    client_secret: 5p4235vobOphyj2MOvPPGXo6PgvBfGuwxVlV3TuMpxOuSOi5bdm3RzOa9p1i5_1r 
    domain: sso.jetprivilege.com
    callback_url: https://delights.jetprivilege.com/auth/auth0/callback
    sso_url: https://sso.jetprivilege.com
  SIMPL:
    client_secret: 6957e5625897f99b78dd345b59d3b01c
    approval_url: https://approvals-api.getsimpl.com/api/v2/simpl_buy/server/approved
    transaction_url: https://api.getsimpl.com/api/v1.1/transactions
  JET:
    voucher_verification_url: https://vmsservice.jetprivilege.com/jpplprod/promocodes/voucherverification
    voucher_verification_key: wj7EkZOCdW9CRZZmIMySl4H8wmJfd6CS8QYCSmeo
  current_property_hotel_url: https://api.walletbuddy.in